### ISSUE TITLE
Would jquery-pjax work with Zepto? 

### ISSUE THREAD

**Issue by KingScooty** [falsandtru/jquery-pjax#11]
Would jquery pjax work with Zepto? Or does it use a lot of the jQuery API?

**Comment by falsandtru** [comment]
This pjax is dependent on jQuery. It will not work with Zepto.

**Comment by staabm** [comment]
Any plans to get rid of jquery?

**Comment by falsandtru** [comment]
Now this pjax haven't used jquery.
