### ISSUE TITLE
can not load javascript

### ISSUE THREAD

**Issue by dbarma** [falsandtru/jquery-pjax#13]
Hi, pjax is not loading javascript files. When enabling load: {script: true} the page refreshes by it self.
I am using jquery-1.11.3.js

Please guide me

**Comment by falsandtru** [comment]
Hi, this pjax load external script files only once for each script file path. Inline scripts are run every time. Otherwise, this pjax can load external script files every time by `load:{reload:"selector"}` setting, but this is not better solution.

**Comment by falsandtru** [comment]
If you cannot move pages using pjax when setting load: { script: true }, please test your script. If your script cannot load and run multiple times, that is the cause. This is common case.
