### ISSUE TITLE
How can I change url without anchors like $.pjax({url: '/path/file.html'}); ?

### ISSUE THREAD

**Issue by igari** [falsandtru/jquery-pjax#18]
$.pjax.click(url); is not good for my case.

The problem of my case is that focus of input is missing after transition.

**Comment by falsandtru** [comment]
This pjax supports `$.pjax.click('url')` syntax. And this pjax doesn't keep a focus because it is not standard behaviors. You need to focus on the input by yourself on the next page.

**Comment by igari** [comment]
Thank you for quick reply.

Okay. At this time, I use another plugin.

Thank you!
